/**
 * Generates src/buildInfo.ts with current git commit hash and build date.
 * Run before build: `tsx scripts/generateBuildInfo.ts`
 */
import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "..", "src", "buildInfo.ts");

let commitHash = process.env.BUILD_COMMIT || "";
let commitDate = "";

if (!commitHash) {
  try {
    commitHash = execSync("git rev-parse --short HEAD", { encoding: "utf-8" }).trim();
    commitDate = execSync('git log -1 --format=%cd --date=format:"%Y-%m-%d %H:%M"', {
      encoding: "utf-8",
    }).trim();
  } catch {
    commitHash = "unknown";
  }
}

const buildDate = process.env.BUILD_DATE || new Date().toISOString().replace("T", " ").slice(0, 16);

const content = `// Auto-generated by scripts/generateBuildInfo.ts — do not edit manually
export const BUILD_COMMIT = "${commitHash}";
export const BUILD_DATE = "${buildDate}";
export const COMMIT_DATE = "${commitDate}";
`;

writeFileSync(outPath, content, "utf-8");
console.log(`Build info generated: commit=${commitHash}, date=${buildDate}`);
